### ISSUE TITLE
can't find mail_settings module

### ISSUE THREAD

**Issue by dangt85** [lesp/LXF-PiHome-PostWatch#1]
Sorry, I'm new to Python. Is this a Python library I can download or is it a custom file I have to create?

**Comment by lesp** [comment]
Hello :)

mail_settings is something that you will need to create as a separate file in the same directory as "emailer.py"
All it does is contain two variables

email
password

So for example it could contains

```
email = les@bigl.es
password = 123456
```

These represent a real email account which is used to send the email. In the example code I used a gmail account as it was easy to setup.

I hope that this helps.
Best
Les

**Comment by dangt85** [comment]
Thanks Les, I now understand. I pushed my version of it with outlook smpt all in the same file but obscured the pass with environment variables. 

Cheers!
